### ISSUE TITLE
example fails at "getting gene expression" step: hts_verbose undefined in get_reads.mex

### ISSUE THREAD

**Issue by warrenmcg** [ratschlab/rDiff#1]
I recently ran SplAdder on some RNA-Seq data that my lab generated, and André recommended that I use rDiff while he finishes the preparation of the python script that will incorporate rDiff's methodology.

After some troubleshooting, I finally got rDiff to configure and compile correctly. However, when I ran "make example", I received an error that I cannot figure out how to solve. Here is the relevant output:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 2. Differential testing %
%%%%%%%%%%%%%%%%%%%%%%%%%%%

Set the paths
Load configuration
Compute regions common to multiple genes
Compute alternative regions
Measure gene expression
Getting gene expression for: data//example_condition_A_replicate_1.bam
error: get_reads_for_gene: /home/warren/Downloads/rDiff-master/src/../mex/get_reads.mex: failed to load: /home/warren/Downloads/rDiff-master/src/../mex/get_reads.mex: undefined symbol: hts_verbose
error: called from:
error:   /home/warren/Downloads/rDiff-master/src/tools/read_utils/get_reads_for_gene.m at line 8, column 29
error:   /home/warren/Downloads/rDiff-master/src/get_reads_caller.m at line 52, column 10
error:   /home/warren/Downloads/rDiff-master/src/get_read_counts.m at line 32, column 17
error:   /home/warren/Downloads/rDiff-master/src/rdiff.m at line 38, column 5
starting Octave failed
make[1]: *** [param] Error 255
make[1]: Leaving directory `/home/warren/Downloads/rDiff-master/examples'
make: *** [example] Error 2
```

**Comment by philippdre** [comment]
Hi Warren,

could you please tell me whether you have installed the octave developer 
packages and how you have installed rDiff?

Cheers,
Philipp

**Comment by warrenmcg** [comment]
Hi Philipp,

I’m running on Ubuntu 14.04.3 and have already installed the octave developer packages (sudo apt-get install liboctave-dev and the other automatically installed packages) as well as mkoctfile.

I had to modify the configure script because I initially couldn’t figure out how to get it to find the sam.h file from samtools, even in interactive mode (I ended up writing it into the rdiff_config.sh file and commenting out line 54 from the script). I also switched the default interpreter to octave. I then did ./configure and make as the installation instructions asked. I should also mention that the Octave version installed by Ubuntu is 3.8.1.

I’m going to email you the modified configure script, the rdiff_config.sh file that configure makes, and the output from make. Let me know if you need anything else.

Best,
Warren

**Comment by philippdre** [comment]
Could you try to execute:

make clean
make octave

?

Cheers,
Philipp

**Comment by warrenmcg** [comment]
Hi Philipp,

I cd’ed into the mex folder.

make clean output:

```
rm -f *.o *.mexa64 *.mex
```

make octave output:

```
rm -f *.o
/usr/bin/mkoctfile -g --mex get_reads.cpp get_reads_direct.cpp mex_input.cpp read.cpp -I/home/warren/Downloads/samtools-1.2 -L/home/warren/Downloads/samtools-1.2 -lbam -lz -lcurses
rm -f *.o
/usr/bin/mkoctfile -g --mex interval_overlap.cpp
```

I cd’ed into src/locfit/Source and repeated. make clean output:

```
rm -f *.o *.mex *.mexglx *.mexa64
```

make octave output:

```
/usr/bin/mkoctfile -v -g --mex   mexlf.c mlfut.c liblocf.c libmut.c libtube.c liblfev.c 
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  mexlf.c -o mexlf.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  mlfut.c -o mlfut.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  liblocf.c -o liblocf.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  libmut.c -o libmut.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  libtube.c -o libtube.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  liblfev.c -o liblfev.o
liblfev.c: In function ‘getnextdir’:
liblfev.c:4233:3: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   { sprintf(dirnext,"");
   ^
g++ -shared -Wl,-Bsymbolic  -o mexlf.mex  mexlf.o mlfut.o liblocf.o libmut.o libtube.o liblfev.o   -L/usr/lib/x86_64-linux-gnu/octave/3.8.1 -L/usr/lib/x86_64-linux-gnu -loctinterp -loctave -Wl,-Bsymbolic-functions -Wl,-z,relro  
/usr/bin/mkoctfile -v -g --mex   mexpp.c mlfut.c liblocf.c libmut.c libtube.c liblfev.c  
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  mexpp.c -o mexpp.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  mlfut.c -o mlfut.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  liblocf.c -o liblocf.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  libmut.c -o libmut.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  libtube.c -o libtube.o
gcc -c -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/octave-3.8.1/octave/.. -I/usr/include/octave-3.8.1/octave  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -pthread -fopenmp -g   -I.  liblfev.c -o liblfev.o
liblfev.c: In function ‘getnextdir’:
liblfev.c:4233:3: warning: zero-length gnu_printf format string [-Wformat-zero-length]
   { sprintf(dirnext,"");
   ^
g++ -shared -Wl,-Bsymbolic  -o mexpp.mex  mexpp.o mlfut.o liblocf.o libmut.o libtube.o liblfev.o   -L/usr/lib/x86_64-linux-gnu/octave/3.8.1 -L/usr/lib/x86_64-linux-gnu -loctinterp -loctave -Wl,-Bsymbolic-functions -Wl,-z,relro  
cp mexlf.mex ../mex/
cp mexpp.mex ../mex/
```

same error unfortunately.

-Warren

**Comment by philippdre** [comment]
I think the problem has to do with the interface to samtools.

Can you maybe try to install samtools 0.1.17 with the -fPIC option (see 
e.g. https://www.sharcnet.ca/help/index.php/BIO-SAMTOOLS ) and then try 
to reinstall rDiff (with the provided configure script)?

Cheers,
Philipp

**Comment by warrenmcg** [comment]
Hi Philipp,

I forgot to mention that I installed samtools-1.2.1 with the -fPIC option included among the CFLAGS in the Makefile. I redid the process with samtools-0.1.17 (add -fPIC, make; ./configure in rDiff; make clean in /mex and /src/locfit/Source to clean out old files; make octave in each directory; make example). I got a different error this time:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 2. Differential testing %
%%%%%%%%%%%%%%%%%%%%%%%%%%%

Set the paths
Load configuration
Compute regions common to multiple genes
Compute alternative regions
Measure gene expression
Getting gene expression for: data//example_condition_A_replicate_1.bam
error: get_reads_for_gene: /home/warren/Downloads/rDiff-master/src/tools/read_utils/get_reads.mex: failed to load: libcruft.so: cannot open shared object file: No such file or directory
error: called from:
error:   /home/warren/Downloads/rDiff-master/src/tools/read_utils/get_reads_for_gene.m at line 8, column 29
error:   /home/warren/Downloads/rDiff-master/src/get_reads_caller.m at line 52, column 10
error:   /home/warren/Downloads/rDiff-master/src/get_read_counts.m at line 32, column 17
error:   /home/warren/Downloads/rDiff-master/src/rdiff.m at line 38, column 5
starting Octave failed
make[1]: *** [param] Error 255
make[1]: Leaving directory `/home/warren/Downloads/rDiff-master/examples'
make: *** [example] Error 2
```

Samtools was reorganized to be separate from HTSLib in later releases (1.x) [link to new website](http://www.htslib.org), so however you designed the dependencies with Samtools/HTSLib was probably disrupted and this may be causing the original error, but I’m not sure what the new error means.

-Warren

**Comment by philippdre** [comment]
Hi Warren,

I think that might have to do with the octave version as somebody using Octave 3.8.1 reported it before. This is how he solved it:

This problem has been solved : an old version of octave have been downloaded (3.4.1) and its libraries have been built. Those libraries have been added in the path and symbolic links have been done to satisfy rDiff name-space requirements. I am using Octave 3.8.1, the version that is available on ubuntu 14.04 official repositories.

Two libraries were in this particular case : libcruft.so (built from Octave 3.4.1) and libhdf5.so.0.6 (symbolically linked to libhdf5.so) Please, note that a colleague of mine, who works under CentOS environment, does not experience any of those issues (Octave 3.4.3 is (one of?) the default version available on officials repositories).

Does this help?

Cheers,
Philipp

**Comment by warrenmcg** [comment]
Hi Philipp,

Maybe, but I've got more issues and I've been getting very frustrated with build errors when attempting to build Octave 3.4.3 or Octave 3.4.1. The current error I'm trying to debug is this one, starting from the compilation line that produced the error:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../libgnu -I../libgnu -I../libcruft/misc -g -O2 -DHAVE_CONFIG_H -I/usr/include/freetype2 -I/usr/include/freetype2 -Wall -W -Wshadow -Wold-style-cast -Wformat -Wpointer-arith -Wwrite-strings -Wcast-align -Wcast-qual -g -O2 -pthread -g -O2 -MT liboctave_la-MArray-i.lo -MD -MP -MF .deps/liboctave_la-MArray-i.Tpo -c MArray-i.cc  -fPIC -DPIC -o .libs/liboctave_la-MArray-i.o
In file included from MArray-i.cc:27:0:
oct-inttypes.h: In instantiation of 'static T octave_int_arith_base<T, true>::mul(T, T) [with T = signed char]':
oct-inttypes.h:815:3:   required from 'octave_int<T>& octave_int<T>::operator*=(const octave_int<T>&) [with T = signed char]'
mx-inlines.cc:94:1:   required from 'void mx_inline_mul2(size_t, R*, X) [with R = octave_int<signed char>; X = octave_int<signed char>; size_t = long unsigned int]'
MArray.cc:243:49:   required from 'MArray<T>& operator*=(MArray<T>&, const T&) [with T = octave_int<signed char>]'
MArray-i.cc:45:1:   required from here
oct-inttypes.h:625:53: error: 'truncate_int' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
                            * static_cast<mptype> (y));
                                                     ^
oct-inttypes.h:625:53: note: declarations in dependent base 'octave_int_base<signed char>' are not found by unqualified lookup
oct-inttypes.h:625:53: note: use 'octave_int_arith_base::truncate_int' instead
oct-inttypes.h: In instantiation of 'static T octave_int_arith_base<T, true>::mul(T, T) [with T = short int]':
oct-inttypes.h:815:3:   required from 'octave_int<T>& octave_int<T>::operator*=(const octave_int<T>&) [with T = short int]'
mx-inlines.cc:94:1:   required from 'void mx_inline_mul2(size_t, R*, X) [with R = octave_int<short int>; X = octave_int<short int>; size_t = long unsigned int]'
MArray.cc:243:49:   required from 'MArray<T>& operator*=(MArray<T>&, const T&) [with T = octave_int<short int>]'
MArray-i.cc:46:1:   required from here
oct-inttypes.h:625:53: error: 'truncate_int' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
oct-inttypes.h:625:53: note: declarations in dependent base 'octave_int_base<short int>' are not found by unqualified lookup
oct-inttypes.h:625:53: note: use 'octave_int_arith_base::truncate_int' instead
oct-inttypes.h: In instantiation of 'static T octave_int_arith_base<T, true>::mul(T, T) [with T = int]':
oct-inttypes.h:815:3:   required from 'octave_int<T>& octave_int<T>::operator*=(const octave_int<T>&) [with T = int]'
mx-inlines.cc:94:1:   required from 'void mx_inline_mul2(size_t, R*, X) [with R = octave_int<int>; X = octave_int<int>; size_t = long unsigned int]'
MArray.cc:243:49:   required from 'MArray<T>& operator*=(MArray<T>&, const T&) [with T = octave_int<int>]'
MArray-i.cc:47:1:   required from here
oct-inttypes.h:625:53: error: 'truncate_int' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
oct-inttypes.h:625:53: note: declarations in dependent base 'octave_int_base<int>' are not found by unqualified lookup
oct-inttypes.h:625:53: note: use 'octave_int_arith_base::truncate_int' instead
oct-inttypes.h: In instantiation of 'static T octave_int_arith_base<T, false>::mul(T, T) [with T = unsigned char]':
oct-inttypes.h:815:3:   required from 'octave_int<T>& octave_int<T>::operator*=(const octave_int<T>&) [with T = unsigned char]'
mx-inlines.cc:94:1:   required from 'void mx_inline_mul2(size_t, R*, X) [with R = octave_int<unsigned char>; X = octave_int<unsigned char>; size_t = long unsigned int]'
MArray.cc:243:49:   required from 'MArray<T>& operator*=(MArray<T>&, const T&) [with T = octave_int<unsigned char>]'
MArray-i.cc:55:1:   required from here
oct-inttypes.h:370:53: error: 'truncate_int' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
                            * static_cast<mptype> (y));
                                                     ^
oct-inttypes.h:370:53: note: declarations in dependent base 'octave_int_base<unsigned char>' are not found by unqualified lookup
oct-inttypes.h:370:53: note: use 'octave_int_arith_base::truncate_int' instead
oct-inttypes.h: In instantiation of 'static T octave_int_arith_base<T, false>::mul(T, T) [with T = short unsigned int]':
oct-inttypes.h:815:3:   required from 'octave_int<T>& octave_int<T>::operator*=(const octave_int<T>&) [with T = short unsigned int]'
mx-inlines.cc:94:1:   required from 'void mx_inline_mul2(size_t, R*, X) [with R = octave_int<short unsigned int>; X = octave_int<short unsigned int>; size_t = long unsigned int]'
MArray.cc:243:49:   required from 'MArray<T>& operator*=(MArray<T>&, const T&) [with T = octave_int<short unsigned int>]'
MArray-i.cc:56:1:   required from here
oct-inttypes.h:370:53: error: 'truncate_int' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
oct-inttypes.h:370:53: note: declarations in dependent base 'octave_int_base<short unsigned int>' are not found by unqualified lookup
oct-inttypes.h:370:53: note: use 'octave_int_arith_base::truncate_int' instead
oct-inttypes.h: In instantiation of 'static T octave_int_arith_base<T, false>::mul(T, T) [with T = unsigned int]':
oct-inttypes.h:815:3:   required from 'octave_int<T>& octave_int<T>::operator*=(const octave_int<T>&) [with T = unsigned int]'
mx-inlines.cc:94:1:   required from 'void mx_inline_mul2(size_t, R*, X) [with R = octave_int<unsigned int>; X = octave_int<unsigned int>; size_t = long unsigned int]'
MArray.cc:243:49:   required from 'MArray<T>& operator*=(MArray<T>&, const T&) [with T = octave_int<unsigned int>]'
MArray-i.cc:57:1:   required from here
oct-inttypes.h:370:53: error: 'truncate_int' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
oct-inttypes.h:370:53: note: declarations in dependent base 'octave_int_base<unsigned int>' are not found by unqualified lookup
oct-inttypes.h:370:53: note: use 'octave_int_arith_base::truncate_int' instead
make[3]: *** [liboctave_la-MArray-i.lo] Error 1
make[3]: Leaving directory `/home/warren/Downloads/octave-3.4.3/liboctave'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/warren/Downloads/octave-3.4.3/liboctave'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/warren/Downloads/octave-3.4.3'
make: *** [all] Error 2
```

What version of gcc was the old version of octave built on (I'm using gcc 4.8.4)? What can I do to troubleshoot these issues?

I apologize that I can't seem to get this to build correctly.

I would suggest looking into seeing if rDiff can be compiled on all versions of octave/samtools from the original versions used through current ones, and modifying the configure or Makefiles if changes to newer versions are breaking the dependencies, or otherwise update the installation instructions so that new users know that only old packages can be used. Most users will not be as persistent as I am in trying to get this to run properly.

**Comment by warrenmcg** [comment]
You know what? It turns out that the libcruft.so library was constructed despite the octave build error. Once I added that to the path, rDiff was able to build correctly and run the example correctly. I still don't think this issue is resolved because rDiff doesn't compile and run out of the box for me unless all of these additional things are done. But for the time being, it appears to be working.

Thanks for your help!
